In [1]:
print('Hello, World')

Hello, World


실행을 위해 shift+Enter를 눌러줍니다.

# 제목1
본문본문본문
## 제목2
### 제목3
1. 항목1
1. 항목2
1. 항목3

*italic*
**bold**<br>
***italic bold***

In [2]:
x = 1

In [3]:
type(x)

int

In [4]:
x = 1.

In [5]:
type(x)

float

In [6]:
x = '1'

In [7]:
type(x)

str

In [8]:
x = 1
y = 1

In [9]:
x + y

2

In [10]:
y = 1.

In [11]:
x + y

2.0

In [12]:
x + x

2

In [13]:
y = '1'

In [14]:
#x + y

In [15]:
x + int(y)

2

In [16]:
y + y

'11'

In [17]:
y * 3

'111'

In [18]:
name = 'python'
이름 = '파이썬'

In [19]:
len(name)

6

In [20]:
len(이름)

3

In [21]:
name[0]

'p'

In [22]:
name[0:3]

'pyt'

In [23]:
name[-3:]

'hon'

In [24]:
리스트 = [1,2,3,4,5,6]

In [25]:
type(리스트)

list

In [26]:
리스트[1:3]

[2, 3]

In [27]:
리스트 * 2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [28]:
list2 = ['가', '나', '다']

In [29]:
리스트 + list2

[1, 2, 3, 4, 5, 6, '가', '나', '다']

In [30]:
리스트

[1, 2, 3, 4, 5, 6]

In [31]:
리스트.extend(['a', 'b', 'c'])

In [32]:
리스트

[1, 2, 3, 4, 5, 6, 'a', 'b', 'c']

In [33]:
리스트.append(['a','b','c'])

In [34]:
리스트

[1, 2, 3, 4, 5, 6, 'a', 'b', 'c', ['a', 'b', 'c']]

In [35]:
리스트.pop()

['a', 'b', 'c']

In [36]:
리스트

[1, 2, 3, 4, 5, 6, 'a', 'b', 'c']

In [37]:
딕셔너리 = {'과목':'pycuda', '월':3, '일':26}

In [38]:
type(딕셔너리)

dict

In [39]:
딕셔너리['과목']

'pycuda'

In [40]:
'월' in 딕셔너리

True

In [41]:
26 in 딕셔너리

False

In [42]:
#딕셔너리 * 2

In [43]:
딕셔너리['장소']='대구'

In [44]:
딕셔너리

{'과목': 'pycuda', '월': 3, '일': 26, '장소': '대구'}

In [45]:
26 in 딕셔너리.values()

True

In [46]:
딕셔너리.pop('월')

3

In [47]:
딕셔너리

{'과목': 'pycuda', '일': 26, '장소': '대구'}

In [48]:
리스트 = list()
딕셔너리 = dict()

In [49]:
#리스트[0] = 'a'

In [50]:
리스트.append('a')

In [51]:
리스트

['a']

In [52]:
딕셔너리[0] = 'a'

In [53]:
튜플 = ('pycuda', 3, 26, '대구')

In [54]:
튜플[0]

'pycuda'

In [55]:
#튜플[2] = 27

In [56]:
튜플[1:3]

(3, 26)

In [57]:
월, 일 = 튜플[1:3]

In [58]:
print ("{0}월 {1}일".format(월, 일))

3월 26일


In [59]:
튜플

('pycuda', 3, 26, '대구')

In [60]:
과목, *튜플2 = 튜플

In [61]:
과목

'pycuda'

In [62]:
튜플2

[3, 26, '대구']

In [63]:
튜플2 = tuple(튜플2)

In [64]:
튜플2

(3, 26, '대구')

In [65]:
안예쁜튜플 = ( 1, 튜플2, [list(튜플2), 딕셔너리] )

In [66]:
안예쁜튜플

(1, (3, 26, '대구'), [[3, 26, '대구'], {0: 'a'}])

In [67]:
안예쁜튜플[1][2]

'대구'

In [68]:
안예쁜튜플[2].append(딕셔너리)

In [69]:
안예쁜튜플

(1, (3, 26, '대구'), [[3, 26, '대구'], {0: 'a'}, {0: 'a'}])

In [70]:
안예쁜딕셔너리 = {'안예쁜튜플':안예쁜튜플}

In [71]:
안예쁜딕셔너리

{'안예쁜튜플': (1, (3, 26, '대구'), [[3, 26, '대구'], {0: 'a'}, {0: 'a'}])}

In [72]:
안예쁜딕셔너리['안예쁜튜플'][2][1][0]

'a'

In [73]:
import numpy as np

In [74]:
일차원배열 = np.array([1, 2, 3, 4])

In [75]:
일차원배열.shape

(4,)

In [76]:
이차원배열 = np.array([[1,2,3],[4,5,6]])

In [77]:
이차원배열.shape

(2, 3)

In [78]:
이차원배열

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
print(이차원배열)

[[1 2 3]
 [4 5 6]]


In [80]:
len(일차원배열)

4

In [81]:
len(이차원배열)

2

In [82]:
print(이차원배열)

[[1 2 3]
 [4 5 6]]


In [83]:
print(이차원배열*2)

[[ 2  4  6]
 [ 8 10 12]]


In [84]:
print(이차원배열 + [10,20,30])

[[11 22 33]
 [14 25 36]]


In [85]:
print(이차원배열 + [ [10], [20] ])

[[11 12 13]
 [24 25 26]]


In [86]:
이차원배열**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [87]:
(이차원배열**2)//10

array([[0, 0, 0],
       [1, 2, 3]], dtype=int32)

In [88]:
print(이차원배열)

[[1 2 3]
 [4 5 6]]


In [89]:
min = 이차원배열.min()

In [90]:
max = 이차원배열.max()

In [91]:
print ("최소값: {0}, 최대값: {1}".format(min, max))

최소값: 1, 최대값: 6


In [92]:
표준화 = ( 이차원배열 - min ) / (max - min)

In [93]:
print(표준화)

[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


In [94]:
row방향평균 = 이차원배열.mean(axis=0)

In [95]:
print(row방향평균)

[2.5 3.5 4.5]


In [96]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
이차원배열

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.ones(이차원배열.shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [99]:
np.full(이차원배열.shape, 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [100]:
np.full_like(이차원배열, 0.5)

array([[0, 0, 0],
       [0, 0, 0]])

In [101]:
np.full_like(이차원배열, 0.5, dtype=np.float)

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [102]:
이차원배열

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.array(range(6))

array([0, 1, 2, 3, 4, 5])

In [104]:
np.array(range(1,7))

array([1, 2, 3, 4, 5, 6])

In [105]:
새배열 = np.array(range(1,7)).reshape( 이차원배열.shape )

In [106]:
새배열

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
이차원배열 == 새배열

array([[ True,  True,  True],
       [ True,  True,  True]])

In [108]:
np.array(range(1,7,2))

array([1, 3, 5])

In [109]:
배열4x4 = np.array(range(16)).reshape( (4,4) )

In [110]:
배열4x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
배열4x4[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [112]:
배열4x4[ [0,2] ]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [113]:
배열4x4[ :, [-3,-1] ]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [114]:
import pandas

In [115]:
#탑5 = pandas.read_clipboard()

In [116]:
#탑5

In [117]:
#탑5[0:1]

In [118]:
#탑5['종목명']

In [119]:
리스트 = [1, 7, 10, 70, 100, 700]

In [120]:
합계 = 0
for n in 리스트:
    합계 = 합계 + n
print(합계)

888


In [121]:
합계 = 0
for n in range(6):
    합계 = 합계 + 리스트[n]
print(합계)

888


In [122]:
합계 = np.array(리스트).sum()
print(합계)

888


In [123]:
for row in 배열4x4:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]


In [124]:
n = 0
while (n < 3):
    print(n)
    n = n + 1

0
1
2


In [125]:
#while True:
#    continue

In [126]:
while True:
    break

In [127]:
while False:
    pass
else:
    print("do not enter while")

do not enter while


In [128]:
리스트 = list(range(5))

In [129]:
리스트

[0, 1, 2, 3, 4]

In [130]:
리스트2 = []
for n in 리스트:
    리스트2.append(n*2)

In [131]:
리스트2

[0, 2, 4, 6, 8]

In [132]:
리스트22 = [ n*2 for n in 리스트]

In [133]:
리스트22

[0, 2, 4, 6, 8]

In [134]:
if 10 in 리스트2:
    print("10 in list")
elif 8 in 리스트2:
    print("8 in list")
else:
    print("Fail")

8 in list


In [135]:
길이 = "길다" if len(리스트2) > 4 else len(리스트2)

In [136]:
길이

'길다'

In [137]:
길이 = "짧다" if len(리스트2) < 4 else len(리스트2)

In [138]:
길이

5

In [139]:
def 두번반복(문자열="Hello"):
    결과 = 문자열*2
    return 결과

In [140]:
두번반복()

'HelloHello'

In [141]:
두번반복("Hi~")

'Hi~Hi~'

In [142]:
def 세번반복(문자열="Hi"):
    return 문자열, 문자열, 문자열

In [143]:
세번반복()

('Hi', 'Hi', 'Hi')

In [144]:
한번, 두번, 세번 = 세번반복("안녕")

In [145]:
한번

'안녕'

In [146]:
def 반복(반복함수, 문자열):
    결과 = 반복함수(문자열)
    return 결과

In [147]:
반복(세번반복, "안녕")

('안녕', '안녕', '안녕')

In [148]:
반복(두번반복, "Hello")

'HelloHello'

In [149]:
반복함수들 = dict()
반복함수들[2] = 두번반복
반복함수들[3] = 세번반복

In [150]:
반복함수들[2]()

'HelloHello'

In [151]:
반복함수들[3]("안녕")

('안녕', '안녕', '안녕')