In [1]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import np_utils

/home/wooyang/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/wooyang/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
from keras.datasets import mnist
 
# Load pre-shuffled MNIST data into train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape, X_test.shape

((60000, 28, 28), (10000, 28, 28))

In [4]:
y_train.shape, y_test.shape

((60000,), (10000,))

In [5]:
from matplotlib import pyplot as plt
plt.imshow(X_train[0])

In [6]:
X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

In [7]:
X_train.shape, X_test.shape

((60000, 28, 28, 1), (10000, 28, 28, 1))

In [8]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [9]:
y_train,y_test

(array([5, 0, 4, ..., 5, 6, 8], dtype=uint8),
 array([7, 2, 1, ..., 4, 5, 6], dtype=uint8))

In [10]:
Y_train = np_utils.to_categorical(y_train, 10)
Y_test = np_utils.to_categorical(y_test, 10)

In [11]:
Y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [12]:
model = Sequential()

In [13]:
model.add(Conv2D(
    32, kernel_size=3, padding='same', input_shape=(28, 28, 1),
    activation='relu'
))
model.add(MaxPooling2D(pool_size=(2,2)))

In [14]:
model.add(Conv2D(
    32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

In [15]:
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 32)        9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 7, 7, 32)          0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 7, 7, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1568)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               200832    
__________

In [18]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [19]:
history = model.fit(
    X_train, Y_train, batch_size=128, epochs=20, 
    validation_split=0.2)

Train on 48000 samples, validate on 12000 samples
Epoch 1/20
48000/48000 [==============================] - 17s 357us/step - loss: 0.3940 - acc: 0.8757 - val_loss: 0.0873 - val_acc: 0.9740
Epoch 2/20
48000/48000 [==============================] - 3s 68us/step - loss: 0.1298 - acc: 0.9595 - val_loss: 0.0627 - val_acc: 0.9810
Epoch 3/20
48000/48000 [==============================] - 3s 68us/step - loss: 0.0984 - acc: 0.9694 - val_loss: 0.0482 - val_acc: 0.9858
Epoch 4/20
48000/48000 [==============================] - 3s 69us/step - loss: 0.0819 - acc: 0.9745 - val_loss: 0.0414 - val_acc: 0.9877
Epoch 5/20
48000/48000 [==============================] - 3s 72us/step - loss: 0.0704 - acc: 0.9780 - val_loss: 0.0367 - val_acc: 0.9899
Epoch 6/20
48000/48000 [==============================] - 3s 71us/step - loss: 0.0619 - acc: 0.9810 - val_loss: 0.0352 - val_acc: 0.9895
Epoch 7/20
48000/48000 [==============================] - 3s 69us/step - loss: 0.0574 - acc: 0.9829 - val_loss: 0.0332 - val_a

In [20]:
from pandas import DataFrame
DataFrame(history.history)[-5:]

acc      loss   val_acc  val_loss
15  0.990479  0.030587  0.992667  0.027809
16  0.989917  0.030723  0.991333  0.030322
17  0.989854  0.030010  0.992333  0.030739
18  0.990896  0.027616  0.991750  0.034214
19  0.990917  0.027336  0.992083  0.027810

In [21]:
%map
DataFrame(history.history).plot()